- id: sync-poetry-pre-commit
  name: sync-poetry-pre-commit
  description: Sync the versions of poetry dependencies with pre-commit hooks
  entry: sync-poetry-pre-commit
  language: python
  files: '(.pre-commit-config.yaml|pyproject.toml|poetry.lock)'
  pass_filenames: false
